import type { InferGetServerSidePropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
var dict = require('../asset/dict.json')
import { GetServerSideProps } from 'next'
import React, { useState } from 'react';


function randomPick<Type>(items: Array<Type>): Type {
    return items[Math.floor(Math.random() * items.length)]
};


function shuffle<Type>(array: Array<Type>): Array<Type>{
  return array.sort(() =>0.5 - Math.random());
}

// This gets called on every request
export const getServerSideProps: GetServerSideProps = async () => {
    type DictionaryEntry = {entry: {form: string }}

    const word = randomPick<DictionaryEntry>(dict.words)
    const otherWords = dict.words.filter((w: { entry: { form: string } }) => w.entry.form !== word.entry.form)
    return { props: { word, otherWords } }
}

const setNewQuestion = (setQuestionCallback: Function) => {
    type DictionaryEntry = {entry: {form: string }}
    const word = randomPick<DictionaryEntry>(dict.words).entry.form

    const otherWords = dict.words.filter((w: { entry: { form: string } }) => w.entry.form !== word)
    const shuffledOtherWords = shuffle(otherWords)
    const answerAlternatives = shuffledOtherWords.slice(0, 5).map((e: DictionaryEntry) => e.entry.form)
    setQuestionCallback({word: word, answerAlternatives})
}

const Home: NextPage = ({word, otherWords} : InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const [question, setQuestion] = useState({word: 'a', answerAlternatives: ['o']});
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.big_glyph}>
          {question.word}
        </div>
        <div>
          {shuffle([question.word, ...question.answerAlternatives]).map((a, i) => {
            return (
              <div>
                <button onClick={() => setNewQuestion(setQuestion)}>{a}</button><br/>
              </div>
            )
          })}
        </div>

      </main>


      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
