import type { InferGetServerSidePropsType, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
var dict = require('../asset/dict.json')
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'

function randomPick<Type>(items: Array<Type>): Type {
    return items[Math.floor(Math.random() * items.length)]
};

// This gets called on every request
export const getServerSideProps: GetServerSideProps = async () => {
    const word = randomPick<Any>(dict.words)
    const otherWords = dict.words.filter((w: { entry: { form: string } }) => w.entry.form !== word.entry.form)
    return { props: { word, otherWords } }
}


const Home: NextPage = ({word, otherWords} : InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.big_glyph}>
          {word.entry.form}
        </div>
        <div>
          {console.log(word.translations[0].forms)}
          {word.translations[0].forms}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
